services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root_password'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_DATABASE: 'bookstore'
    ports:
      - "3307:3306"

  mongo:
    image: mongo:latest
    container_name: mongo-container
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev_mongo_user
      MONGO_INITDB_ROOT_PASSWORD: dev_mongo_password
      MONGO_INITDB_DATABASE: bookstore
    ports:
      - "27018:27017"